import { readFileSync, writeFileSync, mkdirSync, cpSync, chmodSync, statSync, existsSync, rmSync, readdirSync } from 'fs';
import { inflateRawSync } from 'zlib';
import { execSync } from 'child_process';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');
const exePath = join(projectRoot, 'Claude Setup.exe');
const resourcesDir = join(projectRoot, 'resources');
const tmpDir = join('/tmp', 'claude-extract-' + process.pid);
const MSIX_URL = 'https://claude.ai/api/desktop/win32/x64/msix/latest/redirect';

// ---------------------------------------------------------------------------
// Inclusion filter — which files from the resources directory to keep
// ---------------------------------------------------------------------------
function shouldInclude(relPath) {
  // Always include app.asar
  if (relPath === 'app.asar') return true;

  // Locale JSON files
  if (relPath.endsWith('.json')) return true;

  // Tray and app icons
  if (relPath.startsWith('TrayIconTemplate')) return true;
  if (relPath.startsWith('claude-screen')) return true;

  // Default config
  if (relPath === 'default.clod') return true;

  // Fonts
  if (relPath.startsWith('fonts/')) return true;

  // Seed data
  if (relPath.startsWith('seed/')) return true;

  // Database migrations
  if (relPath.startsWith('drizzle/')) return true;

  // App icon (generated by extractIcon below, not from NuPkg)
  if (relPath === 'icon.png') return true;

  // Linux SSH binaries only
  if (relPath.startsWith('claude-ssh/claude-ssh-linux-')) return true;
  if (relPath === 'claude-ssh/version.txt') return true;

  // Cowork plugin shim (shell script, cross-platform)
  if (relPath === 'cowork-plugin-shim.sh') return true;

  return false;
}

// ---------------------------------------------------------------------------
// Detect source: exe file (legacy) or direct MSIX download
// ---------------------------------------------------------------------------
let sourceDir;
mkdirSync(tmpDir, { recursive: true });

let eocdOffset = -1;
let exe;

if (existsSync(exePath)) {
  console.log('Reading Claude Setup.exe...');
  exe = readFileSync(exePath);

  // Try to find the ZIP EOCD signature (Squirrel.Windows format)
  for (let i = exe.length - 22; i >= Math.max(0, exe.length - 65536); i--) {
    if (exe[i] === 0x50 && exe[i + 1] === 0x4b && exe[i + 2] === 0x05 && exe[i + 3] === 0x06) {
      eocdOffset = i;
      break;
    }
  }
}

if (exe && eocdOffset !== -1) {
  // ---------------------------------------------------------------------------
  // Format A: Squirrel.Windows installer (ZIP with embedded NuPkg)
  // ---------------------------------------------------------------------------
  console.log('Detected Squirrel.Windows installer format');

  const cdSize = exe.readUInt32LE(eocdOffset + 12);
  const cdOffsetRel = exe.readUInt32LE(eocdOffset + 16);
  const cdActual = eocdOffset - cdSize;
  const zipBase = cdActual - cdOffsetRel;
  console.log(`Found embedded ZIP at offset ${zipBase}`);

  if (exe[zipBase] !== 0x50 || exe[zipBase + 1] !== 0x4b || exe[zipBase + 2] !== 0x03 || exe[zipBase + 3] !== 0x04) {
    console.error('Invalid ZIP local file header at calculated offset');
    process.exit(1);
  }

  const compressionMethod = exe.readUInt16LE(zipBase + 8);
  const compressedSize = exe.readUInt32LE(zipBase + 18);
  const fileNameLen = exe.readUInt16LE(zipBase + 26);
  const extraFieldLen = exe.readUInt16LE(zipBase + 28);
  const fileName = exe.subarray(zipBase + 30, zipBase + 30 + fileNameLen).toString('utf8');
  const dataOffset = zipBase + 30 + fileNameLen + extraFieldLen;

  console.log(`Found: ${fileName} (${(compressedSize / 1024 / 1024).toFixed(1)} MB compressed, method=${compressionMethod})`);

  let nupkgData;
  if (compressionMethod === 0) {
    nupkgData = exe.subarray(dataOffset, dataOffset + compressedSize);
  } else if (compressionMethod === 8) {
    console.log('Decompressing NuPkg...');
    const compressed = exe.subarray(dataOffset, dataOffset + compressedSize);
    nupkgData = inflateRawSync(compressed);
  } else {
    console.error(`Unsupported compression method: ${compressionMethod}`);
    process.exit(1);
  }

  console.log(`Decompressed NuPkg: ${(nupkgData.length / 1024 / 1024).toFixed(1)} MB`);

  const nupkgPath = join(tmpDir, 'claude.nupkg');
  writeFileSync(nupkgPath, nupkgData);

  console.log('Extracting NuPkg contents...');
  const extractDir = join(tmpDir, 'nupkg');
  mkdirSync(extractDir, { recursive: true });
  execSync(`unzip -o -q "${nupkgPath}" "lib/net45/resources/*" "lib/net45/claude_ExecutionStub.exe" -d "${extractDir}"`, {
    stdio: 'pipe',
    maxBuffer: 10 * 1024 * 1024,
  });

  sourceDir = join(extractDir, 'lib', 'net45', 'resources');

  // Extract app icon from the stub exe's PE resources
  const stubExePath = join(extractDir, 'lib', 'net45', 'claude_ExecutionStub.exe');
  if (existsSync(stubExePath)) {
    extractIconFromPE(stubExePath, sourceDir);
  } else {
    console.warn('claude_ExecutionStub.exe not found in NuPkg, icon.png will be missing');
  }
} else {
  // ---------------------------------------------------------------------------
  // Format B: Download MSIX directly from Anthropic's API
  // ---------------------------------------------------------------------------
  if (exe) {
    console.log('Detected MSIX bootstrapper — downloading MSIX directly');
  } else {
    console.log('No Claude Setup.exe found — downloading latest MSIX');
  }

  const msixPath = join(tmpDir, 'claude.msix');

  // Check if an MSIX was provided locally
  const localMsix = join(projectRoot, 'Claude.msix');
  if (existsSync(localMsix)) {
    console.log('Using local Claude.msix file');
    cpSync(localMsix, msixPath);
  } else {
    console.log(`Downloading from ${MSIX_URL}...`);
    execSync(`curl -L --progress-bar -o "${msixPath}" "${MSIX_URL}"`, {
      stdio: 'inherit',
      timeout: 5 * 60 * 1000,
    });
  }

  if (!existsSync(msixPath) || statSync(msixPath).size < 10 * 1024 * 1024) {
    console.error('ERROR: MSIX download failed or file is too small');
    process.exit(1);
  }

  console.log(`MSIX: ${(statSync(msixPath).size / 1024 / 1024).toFixed(1)} MB`);

  console.log('Extracting MSIX contents...');
  const extractDir = join(tmpDir, 'msix');
  mkdirSync(extractDir, { recursive: true });
  execSync(`unzip -o -q "${msixPath}" "app/resources/*" "assets/icon.png" -d "${extractDir}"`, {
    stdio: 'pipe',
    maxBuffer: 10 * 1024 * 1024,
  });

  sourceDir = join(extractDir, 'app', 'resources');

  // Copy icon from MSIX assets if available
  const msixIcon = join(extractDir, 'assets', 'icon.png');
  if (existsSync(msixIcon)) {
    cpSync(msixIcon, join(sourceDir, 'icon.png'));
    console.log('  Copied icon.png from MSIX assets');
  }
}

// ---------------------------------------------------------------------------
// Extract app icon from a PE file's resources (used by Squirrel format)
// ---------------------------------------------------------------------------
function extractIconFromPE(pePath, destDir) {
  console.log(`Extracting app icon from ${pePath}...`);
  const pe = readFileSync(pePath);
  const peOff = pe.readUInt32LE(0x3c);
  const optHeaderSize = pe.readUInt16LE(peOff + 20);
  const numSections = pe.readUInt16LE(peOff + 6);
  const magic = pe.readUInt16LE(peOff + 24);
  const isPE32Plus = magic === 0x20b;
  const ddOffset = peOff + 24 + (isPE32Plus ? 112 : 96);
  const resRVA = pe.readUInt32LE(ddOffset + 2 * 8);

  const sectStart = peOff + 24 + optHeaderSize;
  let rsrcVA, rsrcRaw;
  for (let i = 0; i < numSections; i++) {
    const so = sectStart + i * 40;
    if (pe.subarray(so, so + 6).toString('ascii') === '.rsrc\0') {
      rsrcVA = pe.readUInt32LE(so + 12);
      rsrcRaw = pe.readUInt32LE(so + 20);
      break;
    }
  }

  if (rsrcVA == null) return;

  const rvaToFile = (rva) => rva - rsrcVA + rsrcRaw;

  function findIcons(dirOffset) {
    const namedCount = pe.readUInt16LE(dirOffset + 12);
    const idCount = pe.readUInt16LE(dirOffset + 14);
    const entries = [];
    for (let i = 0; i < namedCount + idCount; i++) {
      const eo = dirOffset + 16 + i * 8;
      const id = pe.readUInt32LE(eo) & 0xFFFF;
      const val = pe.readUInt32LE(eo + 4);
      const isDir = (val & 0x80000000) !== 0;
      entries.push({ id, offset: rsrcRaw + (val & 0x7FFFFFFF), isDir });
    }
    return entries;
  }

  const typeEntries = findIcons(rsrcRaw);
  const groupIconType = typeEntries.find(e => e.id === 14);
  const iconType = typeEntries.find(e => e.id === 3);

  if (!groupIconType || !iconType) return;

  const groupEntries = findIcons(groupIconType.offset);
  const langEntries = findIcons(groupEntries[0].offset);
  const groupDataRVA = pe.readUInt32LE(langEntries[0].offset);
  const groupDataSize = pe.readUInt32LE(langEntries[0].offset + 4);
  const groupData = pe.subarray(rvaToFile(groupDataRVA), rvaToFile(groupDataRVA) + groupDataSize);

  const iconCount = groupData.readUInt16LE(4);
  let bestIcon = null;
  let bestSize = 0;

  for (let i = 0; i < iconCount; i++) {
    const e = 6 + i * 14;
    const w = groupData[e] || 256;
    const bytesInRes = groupData.readUInt32LE(e + 8);
    const iconId = groupData.readUInt16LE(e + 12);
    if (w >= bestSize) {
      bestSize = w;
      bestIcon = { id: iconId, bytes: bytesInRes };
    }
  }

  if (!bestIcon) return;

  const iconEntries = findIcons(iconType.offset);
  const iconEntry = iconEntries.find(e => e.id === bestIcon.id);
  if (!iconEntry) return;

  const iconLang = findIcons(iconEntry.offset);
  const dataRVA = pe.readUInt32LE(iconLang[0].offset);
  const dataSize = pe.readUInt32LE(iconLang[0].offset + 4);
  const iconData = pe.subarray(rvaToFile(dataRVA), rvaToFile(dataRVA) + dataSize);

  const isPNG = iconData[0] === 0x89 && iconData[1] === 0x50 &&
                iconData[2] === 0x4e && iconData[3] === 0x47;
  if (isPNG) {
    writeFileSync(join(destDir, 'icon.png'), iconData);
    console.log(`  Extracted ${bestSize}x${bestSize} PNG icon`);
  } else {
    console.warn('  Largest icon is not PNG, skipping (icon.png will be missing)');
  }
}

// ---------------------------------------------------------------------------
// Copy filtered assets to resources/
// ---------------------------------------------------------------------------
console.log('Copying assets to resources/...');

if (existsSync(resourcesDir)) {
  rmSync(resourcesDir, { recursive: true });
}
mkdirSync(resourcesDir, { recursive: true });

function walkAndCopy(dir, relBase) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    // MSIX URL-encodes @ as %40 in filenames — decode for the filter and destination
    const decodedName = decodeURIComponent(entry.name);
    const relPath = relBase ? `${relBase}/${decodedName}` : decodedName;
    if (entry.isDirectory()) {
      walkAndCopy(fullPath, relPath);
    } else if (shouldInclude(relPath)) {
      const destPath = join(resourcesDir, relPath);
      mkdirSync(dirname(destPath), { recursive: true });
      cpSync(fullPath, destPath);
    }
  }
}

walkAndCopy(sourceDir, '');

// chmod +x Linux SSH binaries
const sshDir = join(resourcesDir, 'claude-ssh');
if (existsSync(sshDir)) {
  for (const name of readdirSync(sshDir)) {
    if (name.startsWith('claude-ssh-linux-')) {
      chmodSync(join(sshDir, name), 0o755);
      console.log(`  chmod +x claude-ssh/${name}`);
    }
  }
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------
const asarPath = join(resourcesDir, 'app.asar');
if (!existsSync(asarPath)) {
  console.error('ERROR: app.asar not found in extracted resources!');
  process.exit(1);
}
const asarSize = statSync(asarPath).size;
if (asarSize < 15 * 1024 * 1024) {
  console.error(`ERROR: app.asar is too small (${asarSize} bytes). Expected >15 MB.`);
  process.exit(1);
}

let fileCount = 0;
function countFiles(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) countFiles(join(dir, entry.name));
    else fileCount++;
  }
}
countFiles(resourcesDir);

console.log(`\nExtraction complete!`);
console.log(`  app.asar: ${(asarSize / 1024 / 1024).toFixed(1)} MB`);
console.log(`  Total files: ${fileCount}`);
console.log(`  Output: ${resourcesDir}`);

// Cleanup tmp
rmSync(tmpDir, { recursive: true });
